<a href="https://colab.research.google.com/github/kunjkinger/tensor_flow/blob/main/tf_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import tensorflow_probability as tfp

In [2]:
print(tf.__version__)

2.5.0


In [3]:
#creating tensors with tf.constant()

In [4]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#checking no of dimensions ndim
scalar.ndim

0

In [6]:
#cerating a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
#check the dimension of the vector
vector.ndim

1

In [8]:
#creta a matrix 
vector = tf.constant([[10,7],
                      [7,10]])
vector

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
vector.ndim

2

In [10]:
#cerate another mATrix
another_matrix = tf.constant([[10.,7.],
                              [2.,2.],
                              [8.,9.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 2.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
 another_matrix.ndim

2

In [12]:
 #lets create a tensor

In [13]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim

3

In [15]:
#creating tnesors with variable

In [18]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [19]:
#try to change
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [20]:
#try .assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [21]:
#unchagenablee
unchangeable_tensor[0] = 7

TypeError: ignored

In [22]:
unchangeable_tensor.assign(7)

AttributeError: ignored

In [23]:
#creating random tensors
#2 random but same tensor

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [24]:
#shuffle the order of elements in a tensor

not_shuffled = tf.constant([[20,7],
                            [34,5],
                            [65,4]])


In [25]:

tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[65,  4],
       [34,  5],
       [20,  7]], dtype=int32)>

In [26]:
tf.random.set_seed(42)

tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20,  7],
       [34,  5],
       [65,  4]], dtype=int32)>

In [27]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20,  7],
       [34,  5],
       [65,  4]], dtype=int32)>

In [28]:
import numpy as np


In [29]:
numpy_a = np.arange(1,25,dtype=np.int32)

In [30]:
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [31]:
a = tf.constant(numpy_a,shape = (2,3,4))
a

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [32]:
#getting information from the tensors
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
rank_4_tensor.shape, tf.size(rank_4_tensor), rank_4_tensor.ndim

(TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>, 4)

In [34]:
#getting the various attributes of our tensor
print('datatype of every element: ',rank_4_tensor.dtype)
print('Number of dimensions: ', rank_4_tensor.ndim)
print('shape of our tensor: ', rank_4_tensor.shape)
print('elements along the 0 axis: ',rank_4_tensor.shape[0])
print('elements along the last axis: ',rank_4_tensor.shape[-1])
print('total number of elements in our tensor: ', tf.size(rank_4_tensor))

print('total number of elements in our tensor: ', tf.size(rank_4_tensor).numpy())

datatype of every element:  <dtype: 'float32'>
Number of dimensions:  4
shape of our tensor:  (2, 3, 4, 5)
elements along the 0 axis:  2
elements along the last axis:  5
total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
total number of elements in our tensor:  120


In [35]:
# making 3d from 2d tensors keeping the same info
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [36]:
#getting the last column
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [37]:
#making 3d
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [38]:
#alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # axis -1 means expand thr final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [39]:
#alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=0) # axis 0 means expand from the front

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [40]:
x = tf.constant([1,23,4,5])

tf.multiply(x,x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([  1, 529,  16,  25], dtype=int32)>

In [41]:
x

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1, 23,  4,  5], dtype=int32)>

In [42]:
# matrix multiplication
tensor = tf.constant([[1,2],
                      [3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [43]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [44]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [45]:
x = tf.constant([[1,2,5],
                 [7,2,1],
                 [3,3,3]])

y = tf.constant([[3,5],
                 [6,7],
                 [1,8]])

x, y

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [46]:
tf.matmul(x,y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [47]:
x @ y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [48]:
x = tf.constant([[1,2],
                 [7,2],
                 [3,3]])

y = tf.constant([[3,5],
                 [6,7],
                 [1,8]])

x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [7, 2],
        [3, 3]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [49]:
x @ y

InvalidArgumentError: ignored

In [50]:
x @ tf.transpose(y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 20, 17],
       [31, 56, 23],
       [24, 39, 27]], dtype=int32)>

In [51]:
x @ tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17,  7, 22],
       [35, 37, 58],
       [30, 18, 42]], dtype=int32)>

In [52]:
y, tf.transpose(y), tf.reshape(y , shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 6, 1],
        [5, 7, 8]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 5, 6],
        [7, 1, 8]], dtype=int32)>)

In [53]:
#mTRIX MULTIPLIACTION WITH 
#tf.tensordot()

In [54]:
tf.tensordot(x , tf.transpose(y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 20, 17],
       [31, 56, 23],
       [24, 39, 27]], dtype=int32)>

In [55]:
#changing the datatype of a tensor

In [56]:
B = tf.constant([1.7,3.4])
B.dtype

tf.float32

In [57]:
C = tf.constant([4,5])
C.dtype

tf.int32

In [58]:
# from float 32 to float 16
B = tf.cast(B, dtype=tf.float16)
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 3.4], dtype=float16)>,
 tf.float16)

In [59]:
C = tf.cast(C, dtype=tf.float32)
C.dtype

tf.float32

In [60]:
#aggregating the tensors
#converting from multiple values down to smaller amount of values

In [61]:
D= tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [62]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [63]:
#create a random tensor

E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([18, 93,  6, 76,  5, 33, 11,  6, 78, 35, 85, 84, 69, 52, 26, 89, 48,
       88, 84, 44,  6, 76, 80,  8,  6, 72, 54, 77, 65, 33, 10, 15, 19,  1,
       56, 67,  0, 87, 71, 20, 79,  9, 16, 55, 39, 63, 60, 51, 28, 31])>

In [64]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [65]:
#finding the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [66]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=93>

In [67]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [68]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2284>

In [69]:
# for stats we have to use tfp

In [70]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=889>

In [71]:
#std dev
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.809689>

In [72]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=888.61755>

In [73]:
#creating a new_tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F, tf.size(F), F.shape, F.ndim

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>,
 TensorShape([50]),
 1)

In [74]:
tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [75]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [76]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [77]:
##sequencing thr tensor

In [78]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [79]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [80]:
G_squeeze = tf.squeeze(G) # remove dimensions of size 1 from ther shape of the tensor
G_squeeze, G.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([1, 1, 1, 1, 50]))

In [82]:
#one-hot encoding
some_list = [0,1,2,3] # eg red,green,blue,purple
depth = 4
tf.one_hot(some_list,depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [84]:
#specify custom values for one hot encoding
tf.one_hot(some_list, depth,on_value='yo I love deep elarning',off_value='I also love dance') # in the form of 1000,0100,0010,0001

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep elarning', b'I also love dance',
        b'I also love dance', b'I also love dance'],
       [b'I also love dance', b'yo I love deep elarning',
        b'I also love dance', b'I also love dance'],
       [b'I also love dance', b'I also love dance',
        b'yo I love deep elarning', b'I also love dance'],
       [b'I also love dance', b'I also love dance', b'I also love dance',
        b'yo I love deep elarning']], dtype=object)>

In [85]:
#squaring, log, square root
H =tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [86]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [88]:
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [91]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [94]:
#create a tensor directly from a numpy array
J = tf.constant(np.array([2.,3.,5]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 5.])>

In [95]:
np.array(J), type(np.array(J))

(array([2., 3., 5.]), numpy.ndarray)

In [97]:
#convert tensor J to a numpy array
J.numpy(), type(J.numpy())

(array([2., 3., 5.]), numpy.ndarray)

In [99]:
#default types of each are slightly different

numpy_j = tf.constant(np.array([1.,2.,4.]))
tensor_j = tf.constant([1.,2.,3.])

#check the datatypes
numpy_j.dtype, tensor_j.dtype

(tf.float64, tf.float32)

finding access to the GPUs

In [2]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Wed Jul 28 00:21:24 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------